### PR TITLE
Ubuntu 18.04 Image for All PHP Versions

### PR DESCRIPTION
**Pull request by ElusiveMind**
This is a big PR. It is for every version of PHP 5.6 - 7.3 (PHP 5.5 not supported). I am looking for some initial feedback. A few items of note:

1. It appears to fix the "mysql going away" bug experienced in 14.04 and 16.04
2. Includes MailCatcher which I understand is not a ProboCI feature but is something I use on my personal server. I can remove it for the final PR.
3. Just added Varnish this morning. Not yet tested. Doing that today

Need to know if backporting to Ubuntu 14.04 and 16.04 are really necessary in light of advancements here.

### CODE REVIEW

**Comment by sk33lz** [comment]
This is great Mike! We were just talking about or plan on how to address the 14.04 EOL and rolling out some 18.04 images. This lines up perfectly with what we discussed and will help speed up that process considerably! I can only see a few things that we need to add that I don't think I even had gotten into the Dockerfile config you forked yet like wp-cli, which is used by the Probo Wordpress plugin to install and configure sites, and some of the newer tools we have added like Google's lighthouse testing tool. This is all looking really good so far. I'll go over things with @kleinmp on Monday and we can probably get this merged and work from there to add the other missing pieces to get these ready for primetime. Thanks again Mike!

**Comment by sk33lz** [comment]
One of the things we discussed was focusing mainly on the PHP and MySQL versions and not so much the OS version in future releases to reduce maintenance overhead. We were planning on going with 18.04 for the base OS since it's the latest LTS, as long as we could get the PHP and MySQL setups correct. It looks like you are most of the way there, so this works out great with our plan of attack. I'll get back to you sometime on Monday about this and we can move forward from there.

**Comment by sk33lz** [comment]
I think I'm going to go ahead and merge this in and we can work on adding in the missing pieces that I never got put in to my original work on this setup in another PR.

**Comment by ElusiveMind** [comment]
That is good. I will be working on images this weekend somewhat and more over the next week and can add those components.

**Pull request merged**
